<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="Sraavan-Sumith" name="myTestNG.DependsOnMethodsTest" tests="9" failures="1" timestamp="24 Nov 2018 03:27:39 GMT" time="0.042" errors="0">
  <testcase name="sub" time="0.035" classname="myTestNG.DependsOnMethodsTest"/>
  <testcase name="add" time="0.000" classname="myTestNG.DependsOnMethodsTest">
    <skipped/>
  </testcase> <!-- add -->
  <testcase name="greater" time="0.002" classname="myTestNG.DependsOnMethodsTest">
    <skipped/>
  </testcase> <!-- greater -->
  <testcase name="greater" time="0.001" classname="myTestNG.DependsOnMethodsTest">
    <failure type="java.lang.AssertionError" message="????? Failing this Test ?????">
      <![CDATA[java.lang.AssertionError: ????? Failing this Test ?????
at org.testng.Assert.fail(Assert.java:96)
at myTestNG.DependsOnMethodsTest.greater(DependsOnMethodsTest.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- greater -->
  <testcase name="greater" time="0.001" classname="myTestNG.DependsOnMethodsTest">
    <skipped/>
  </testcase> <!-- greater -->
  <testcase name="div" time="0.002" classname="myTestNG.DependsOnMethodsTest"/>
  <testcase name="greater" time="0.000" classname="myTestNG.DependsOnMethodsTest">
    <skipped/>
  </testcase> <!-- greater -->
  <testcase name="lesser" time="0.001" classname="myTestNG.DependsOnMethodsTest"/>
  <testcase name="mul" time="0.000" classname="myTestNG.DependsOnMethodsTest">
    <skipped/>
  </testcase> <!-- mul -->
</testsuite> <!-- myTestNG.DependsOnMethodsTest -->
